// Type-checks the add-in (DesignLint/) against the TypeScript definitions bundled with the local
// Fusion install. "@adsk/fusion" is not on npm; Fusion ships it inside its app bundle, in a folder
// whose name changes with every Fusion update, so the path is discovered here.
//
// Writes a machine-specific tsconfig.json at the repo root (gitignored). VS Code picks it up too,
// which gives IntelliSense for the add-in.
//
// Override the location with FUSION_TS_TYPES=/path/to/Api/TypeScript.

import { execFileSync } from "node:child_process";
import { existsSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

function findFusionTypings() {
    if (process.env.FUSION_TS_TYPES) {
        return process.env.FUSION_TS_TYPES;
    }
    // Verified on macOS. The Windows location is assumed to follow the same webdeploy layout.
    const production =
        process.platform === "darwin"
            ? join(homedir(), "Library/Application Support/Autodesk/webdeploy/production")
            : join(process.env.LOCALAPPDATA ?? "", "Autodesk/webdeploy/production");
    if (!existsSync(production)) {
        return null;
    }
    const candidates = readdirSync(production)
        .map((build) =>
            process.platform === "darwin"
                ? join(production, build, "Autodesk Fusion.app/Contents/Api/TypeScript")
                : join(production, build, "Api/TypeScript"),
        )
        .filter((dir) => existsSync(join(dir, "@adsk/fusion/index.d.ts")))
        // Newest install first.
        .sort((a, b) => statSync(b).mtimeMs - statSync(a).mtimeMs);
    return candidates[0] ?? null;
}

const typings = findFusionTypings();
if (!typings) {
    console.error(
        "Could not find Fusion's TypeScript definitions. Install Fusion, or set FUSION_TS_TYPES to the folder that contains @adsk/fusion/index.d.ts.",
    );
    process.exit(1);
}
console.log(`Using Fusion typings: ${typings}`);

const tsconfig = {
    // Generated by scripts/typecheck.mjs for this machine. Do not commit.
    compilerOptions: {
        strict: true,
        noEmit: true,
        target: "ES2022",
        module: "ES2022",
        moduleResolution: "bundler",
        lib: ["ES2022"],
        types: [],
        skipLibCheck: true,
        paths: {
            "@adsk/fusion": [join(typings, "@adsk/fusion/index.d.ts")],
            "@adsk/fusion/*": [join(typings, "@adsk/fusion/*")],
        },
    },
    include: ["DesignLint/**/*.ts"],
};
writeFileSync("tsconfig.json", JSON.stringify(tsconfig, null, 2) + "\n");

try {
    execFileSync(process.execPath, ["node_modules/typescript/bin/tsc", "-p", "tsconfig.json"], { stdio: "inherit" });
    console.log("Add-in type check passed.");
} catch {
    process.exit(1);
}
